---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitops
  namespace: application-samples
spec:
  type: GitHub
  pathname: https://github.com/jnpacker/application-samples.git
