---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: plumbing-placement
  namespace: big-bang
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'