---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: acs-init-bundle-placement
  namespace: stackrox
spec:
  clusterSelector:
    matchLabels:
      'vendor': 'OpenShift'