---
apiVersion: v1
kind: Namespace
metadata:
  name: init-bundle-ch
---
apiVersion: v1
kind: Namespace
metadata:
  name: stackrox
---
apiVersion: v1                      
kind: Namespace
metadata:
  name: ggithubcom-jnpacker-helm-charts-ns
