apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: non-ocp-pull-secrets
  namespace: policy
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-1 Data-at-rest
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: k8s-pull-secrets-namespaces
        spec:
          remediationAction: enforce
          severity: med
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: operators
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: olm
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-gitops
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: k8s-pull-secrets
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: openshift-pull-secret
                  namespace: operators
                  annotations:
                    apps.open-cluster-management.io/deployables: "secret"
                data:
                  .dockerconfigjson: |
                    {{ fromSecret "stackrox" "openshift-pull-secret" ".dockerconfigjson" }}
                type: kubernetes.io/dockerconfigjson
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: openshift-pull-secret
                  namespace: olm
                  annotations:
                    apps.open-cluster-management.io/deployables: "secret"
                data:
                  .dockerconfigjson: | 
                    {{ fromSecret "stackrox" "openshift-pull-secret" ".dockerconfigjson" }}
                type: kubernetes.io/dockerconfigjson
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: openshift-pull-secret
                  namespace: openshift-operators
                  annotations:
                    apps.open-cluster-management.io/deployables: "secret"
                data:
                  .dockerconfigjson: |
                    {{ fromSecret "stackrox" "openshift-pull-secret" ".dockerconfigjson" }}
                type: kubernetes.io/dockerconfigjson
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                imagePullSecrets:
                - name: openshift-pull-secret
                kind: ServiceAccount
                metadata:
                  name: default
                  namespace: operators
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-acs-all-clusters
  namespace: policy
placementRef:
  name: non-openshift
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: non-ocp-pull-secrets
    kind: Policy
    apiGroup: policy.open-cluster-management.io
