---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: all-clusters
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable

          
