---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: non-openshift
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: NotIn
        values:
          - OpenShift
          
