apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: redhat-acs-k8s-installed
  namespace: openshift-config
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-1 Data-at-rest
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: redhat-acs-secrets
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: stackrox
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  namespace: stackrox
                  name: collector-tls
                data:
                  ca.pem: |
                    {{hub fromSecret "openshift-config" "collector-tls" "ca.pem" hub}}
                  collector-cert.pem: |
                    {{hub fromSecret "openshift-config" "collector-tls" "collector-cert.pem" hub}}
                  collector-key.pem: |
                    {{hub fromSecret "openshift-config" "collector-tls" "collector-key.pem" hub}}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  namespace: stackrox
                  name: sensor-tls
                data:
                  acs-host: |
                    {{hub fromSecret "openshift-config" "sensor-tls" "acs-host" hub}}
                  ca.pem: |
                    {{hub fromSecret "openshift-config" "sensor-tls" "ca.pem" hub}}
                  sensor-cert.pem: |
                    {{hub fromSecret "openshift-config" "sensor-tls" "sensor-cert.pem" hub}}
                  sensor-key.pem: |
                    {{hub fromSecret "openshift-config" "sensor-tls" "sensor-key.pem" hub}}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  namespace: stackrox
                  name: admission-control-tls
                data:
                  ca.pem: |
                    {{hub fromSecret "openshift-config" "admission-control-tls" "ca.pem" hub}}
                  admission-control-cert.pem: |
                    {{hub fromSecret "openshift-config" "admission-control-tls" "admission-control-cert.pem" hub}}
                  admission-control-key.pem: |
                    {{hub fromSecret "openshift-config" "admission-control-tls" "admission-control-key.pem" hub}}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: helm-effective-cluster-name
                  namespace: stackrox
                  labels:
                    auto-upgrade.stackrox.io/component: sensor
                  annotations:
                    "helm.sh/hook": "pre-install,pre-upgrade"
                    "helm.sh/resource-policy": "keep"
                stringData:
                  cluster-name: |
                    {{ fromSecret "open-cluster-management-agent" "hub-kubeconfig-secret" "cluster-name" | base64dec }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: managed-cluster-security-endpoints
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: sensor
                  namespace: stackrox
                spec:
                  template:
                    spec:
                      containers:
                      - name: sensor
                        env:
                        - name: ROX_CENTRAL_ENDPOINT
                          value: |
                            {{ fromSecret "stackrox" "sensor-tls" "acs-host" | base64dec }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: service-ca
                  namespace: stackrox
                  labels:
                    auto-upgrade.stackrox.io/component: sensor
                type: Opaque
                stringData:
                  ca.pem: |
                    {{ fromSecret "stackrox" "sensor-tls" "ca.pem" | base64dec }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-acs-k8s-clusters
  namespace: openshift-config
placementRef:
  name: non-openshift
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: redhat-acs-k8s-installed
    kind: Policy
    apiGroup: policy.open-cluster-management.io
