---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: infrastructure-buildout
  namespace: seeds
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'