---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: seeds
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: infrastructure-buildout
  name: infrastructure-buildout
  namespace: seeds
spec:
  channel: big-bang/gitops-fleet-samples
  placement:
    #local: true
    placementRef:
      kind: PlacementRule
      name: infrastructure-buildout

