---
apiVersion: v1
kind: Namespace
metadata:
  name: tower
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/awx-resource-operator.tower: ''
  name: awx-resource-operator
  namespace: tower
spec:
  channel: release-0.1
  installPlanApproval: Automatic
  name: awx-resource-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: awx-resource-operator.v0.1.1