apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: mortgage-app-placement
  namespace: mortgage
  labels:
    app: mortgage-app
spec:
  resourceHint:
    type: memory
    order: desc
  clusterReplicas: 1
  clusterSelector:
    matchExpressions:
      - key: usage
        operator: In
        values:
          - production
