apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mortgage-app-subscription
  namespace: mortgage
  labels:
    app: mortgage-app
  annotations:
    apps.open-cluster-management.io/github-path: mortgage
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: application-samples/gitops
  placement:
    placementRef:
      name: mortgage-app-placement
      kind: PlacementRule
      group: apps.open-cluster-management.io