---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: operator-lifecycle-management-k8s
  name: operator-lifecycle-management-k8s-placement-1
  namespace: olm
spec:
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: NotIn
        values:
          - OpenShift
