---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: olm-k8s
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: operator-lifecycle-management-k8s
  name: operator-lifecycle-management-k8s-subscription-1
  namespace: olm
spec:
  channel: big-bang/gitops-fleet-samples
  placement:
    placementRef:
      kind: PlacementRule
      name: operator-lifecycle-management-k8s-placement-1