---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
    name: cloudprovider-quotacheck
subjects:
- kind: User
  name: system:serviceaccount:openshift-gitops:cloudprovider-quotacheck # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cloudprovider-quotacheck
  apiGroup: rbac.authorization.k8s.io