apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: ansible-automation-platform-operator-installed
  namespace: policy
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-1 Data-at-rest
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: ansible-automation-platform-operator-installed
        spec:
          remediationAction: enforce
          severity: med
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: ansible-automation-platform
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  labels:
                    operators.coreos.com/ansible-automation-platform-operator.ansible-automation-platfor: ''
                  name: ansible-automation-platform-operator
                  namespace: ansible-automation-platform
                spec:
                  channel: early-access-cluster-scoped
                  installPlanApproval: Automatic
                  name: ansible-automation-platform-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
                  startingCSV: aap-operator.v2.0.1-0.1635283332
